network:
  protocol: ${BLOCKCHAIN_PROTOCOL:ws}
  host: ${BLOCKCHAIN_HOST:localhost}
  port: ${BLOCKCHAIN_PORT:8545}
  path: ${BLOCKCHAIN_PATH:}

subscriptions:
  - contract_address: ${CONTRACT_ADDRESS:0x061b3e39A7f08F739641D31b9aD5795B3a34159f}
    events:
      - "TransferExecuted(address,address)"
  - contract_address: ${CONTRACT_ADDRESS:0x27FcDf131c8401ac27955d6116a2E90f3293683a}
    events:
      - "Approval(address,address)"
  - contract_address: ${CONTRACT_ADDRESS:0x5FbDB2315678afecb367f032d93F642f64180aa3}
    events:
      - "DummyStructCreated(uint256,uint256,int256,bool,string,bytes32)"
  - contract_address: ${CONTRACT_ADDRESS:0x5FbDB2315678afecb367f032d93F642f64180aa3}
    events:
      - "DummyStructUpdated(uint256,uint256,int256,bool,string,bytes32)"